const $=id=>document.getElementById(id);
const API=window.location.origin;
const poster=p=>p?`https://image.tmdb.org/t/p/w500${p}`:'';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=n=>new Intl.NumberFormat('pl-PL').format(n||0);
function params(){const p=new URLSearchParams();const c=$("country").value;if(c)p.set('production_country',c);p.set('content_type',$("type").value);p.set('min_rating',$("rating").value);p.set('min_votes',$("votes").value);p.set('sort',$("sort").value);p.set('region','DK');p.set('limit',$("limit").value);return p}
function sortLabel(v){return ({rating:'ocenie',votes:'liczbie głosów',popularity:'popularności'})[v]}
function render(items){const root=$("results");if(!items.length){root.innerHTML='<div class="empty">Nie znaleziono tytułów spełniających te kryteria.</div>';return}root.innerHTML=items.map((x,i)=>`<article class="result-card" data-type="${x.type}" data-id="${x.id}"><div class="poster-wrap">${x.poster_path?`<img loading="lazy" src="${poster(x.poster_path)}" alt="${esc(x.title)}">`:'<div class="loading">Brak plakatu</div>'}<span class="rank">#${i+1}</span><span class="score">⭐ ${Number(x.rating||0).toFixed(1)}</span></div><div class="info"><div class="title">${esc(x.title)}</div><div class="meta">${esc(x.year||'')} · ${fmt(x.vote_count)} głosów<br>${x.type==='movie'?'Film':x.type==='miniseries'?'Miniserial':'Serial'}</div></div></article>`).join('');root.querySelectorAll('.result-card').forEach(c=>c.addEventListener('click',()=>openDetails(c.dataset.type,c.dataset.id)))}
async function search(){const btn=$("searchBtn");btn.disabled=true;$("status").textContent='Szukam…';$("results").innerHTML='<div class="loading">Pobieranie wyników…</div>';try{const r=await fetch(`${API}/search?${params()}`);if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();$("resultsTitle").textContent=`TOP ${d.results.length}`;$("resultCount").textContent=`Netflix · DK · sortowanie po ${sortLabel(d.criteria.sort)}`;$("status").textContent='';render(d.results)}catch(e){$("results").innerHTML='<div class="empty">Nie udało się pobrać wyników. Spróbuj ponownie.</div>';$("status").textContent=e.message}finally{btn.disabled=false}}
async function openDetails(type,id){const modal=$("modal"),content=$("modalContent");modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false');content.innerHTML='<div class="loading">Ładowanie szczegółów…</div>';const media=type==='movie'?'movie':'tv';try{const r=await fetch(`${API}/title/${media}/${id}`);if(!r.ok)throw new Error(`HTTP ${r.status}`);const x=await r.json();content.innerHTML=`<div class="detail"><div>${x.poster_url?`<img src="${x.poster_url}" alt="${esc(x.title)}">`:''}</div><div><h3>${esc(x.title)}</h3><div class="detail-meta">${esc(x.year||'')} · ⭐ ${Number(x.rating||0).toFixed(1)} · ${fmt(x.vote_count)} głosów · ${x.type==='movie'?'Film':x.type==='miniseries'?'Miniserial':'Serial'}</div><p>${esc(x.overview||'Brak opisu.')}</p><a class="tmdb-link" target="_blank" rel="noopener" href="${x.tmdb_url}">Otwórz w TMDB ↗</a></div></div>`}catch(e){content.innerHTML='<div class="empty">Nie udało się pobrać szczegółów.</div>'}}
function closeModal(){const m=$("modal");m.classList.add('hidden');m.setAttribute('aria-hidden','true')}
$("searchBtn").addEventListener('click',search);document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});search();
